import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Base Assistant UI",
  description: "Downloadable assistant-ui demo starter generated by Xulux.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body className="font-sans antialiased">{children}</body>
    </html>
  );
}
